

*   Hardik Grover
*   RA2311003011356
*   B2 Section

SECTION A

Q1
Q2
Q3

In [49]:
import pandas as pd
import numpy as np

data = {
    "Employee_ID": [101,102,103,104,105],
    "Salary": [50000, 70000, 69000, 20000, np.nan],
    "Join_Date": ["2022/05/01", "2021/12/19", "2021/12/21", "2021/12/28", "2021/12/15"],
    "Department": ["HR", "Human Resources", "hr", "HR ", "human resources"]
}

df = pd.DataFrame(data)

df

   Employee_ID   Salary   Join_Date       Department
0          101  50000.0  2022/05/01               HR
1          102  70000.0  2021/12/19  Human Resources
2          103  69000.0  2021/12/21               hr
3          104  20000.0  2021/12/28              HR
4          105      NaN  2021/12/15  human resources

In [50]:
#findi=ing anomalies
df["Salary"].describe()

count        4.000000
mean     52250.000000
std      23386.249521
min      20000.000000
25%      42500.000000
50%      59500.000000
75%      69250.000000
max      70000.000000
Name: Salary, dtype: float64

In [51]:
#sus values frequency

df["Salary"].value_counts()

Salary
50000.0    1
70000.0    1
69000.0    1
20000.0    1
Name: count, dtype: int64

In [52]:


df["Salary"] = df["Salary"].replace([999999, -1], np.nan)


df["Salary"].fillna(df["Salary"].median(), inplace=True)

df

/tmp/ipykernel_2358/3114549129.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].median(), inplace=True)

   Employee_ID   Salary   Join_Date       Department
0          101  50000.0  2022/05/01               HR
1          102  70000.0  2021/12/19  Human Resources
2          103  69000.0  2021/12/21               hr
3          104  20000.0  2021/12/28              HR
4          105  59500.0  2021/12/15  human resources

In [53]:
#cleaning and standardization
df["Department"] = df["Department"].str.lower().str.strip()

df["Department"] = df["Department"].replace({
    "hr": "Human Resources",
    "human resources": "Human Resources"
})#standardize the string hr and human resources, to one single Human Resources

df

   Employee_ID   Salary   Join_Date       Department
0          101  50000.0  2022/05/01  Human Resources
1          102  70000.0  2021/12/19  Human Resources
2          103  69000.0  2021/12/21  Human Resources
3          104  20000.0  2021/12/28  Human Resources
4          105  59500.0  2021/12/15  Human Resources

In [79]:


df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")

df

   Employee_ID   Salary  Join_Date       Department
0          101  50000.0 2022-05-01  Human Resources
1          102  70000.0 2021-12-19  Human Resources
2          103  69000.0 2021-12-21  Human Resources
3          104  20000.0 2021-12-28  Human Resources
4          105  59500.0 2021-12-15  Human Resources

**SECTION B**

*    Q1, Q2, Q3

In [55]:
#orders dataset

orders_data = {
    "Order_ID": [1,2,3,4],
    "Product_ID": [101,102,101,103],
    "Quantity": [2, np.nan, 5, 3]
}

DF_Orders = pd.DataFrame(orders_data)

DF_Orders

   Order_ID  Product_ID  Quantity
0         1         101       2.0
1         2         102       NaN
2         3         101       5.0
3         4         103       3.0

In [56]:
#product info dataset

product_data = {
    "Product_ID": [101,102,103],
    "Product_Name": ["Laptop", "Mouse", "Keyboard"],
    "Price": [80000, 5000, 2500]
}

DF_Product_Info = pd.DataFrame(product_data)

DF_Product_Info

   Product_ID Product_Name  Price
0         101       Laptop  80000
1         102        Mouse   5000
2         103     Keyboard   2500

In [76]:
#Backup dataset, to fill in the missing vals
DF_Orders_Backup=pd.DataFrame({
    "Order_ID": [1, 2, 3],
    "Product_ID": [101, 102, 103],
    "Quantity": [2, 1, 5]})

In [58]:
#merge orders and product info dataframes

merged_df = pd.merge(DF_Orders, DF_Product_Info, on="Product_ID")

merged_df

   Order_ID  Product_ID  Quantity Product_Name  Price
0         1         101       2.0       Laptop  80000
1         2         102       NaN        Mouse   5000
2         3         101       5.0       Laptop  80000
3         4         103       3.0     Keyboard   2500

In [59]:
#Sales = Quantity × Price (given)

merged_df["Sales"] = merged_df["Quantity"] * merged_df["Price"]

merged_df

   Order_ID  Product_ID  Quantity Product_Name  Price     Sales
0         1         101       2.0       Laptop  80000  160000.0
1         2         102       NaN        Mouse   5000       NaN
2         3         101       5.0       Laptop  80000  400000.0
3         4         103       3.0     Keyboard   2500    7500.0

In [60]:
pivot_table = merged_df.pivot_table(
    index="Product_Name",
    values="Sales",
    aggfunc="sum"
)
print(pivot_table)

                 Sales
Product_Name
Keyboard        7500.0
Laptop        560000.0
Mouse              0.0

In [77]:
#Using combine_first to update missing vals w/o duplicating rows

DF_Orders_Backup = DF_Orders_Backup.set_index("Order_ID")

DF_Orders["Quantity"] = DF_Orders["Quantity"].combine_first(
    DF_Orders_Backup["Quantity"]
)

DF_Orders = DF_Orders.reset_index()

print(DF_Orders)

   Order_ID  Product_ID  Quantity
0         1         101       2.0
1         2         102       1.0
2         3         101       5.0
3         4         103       3.0